!!python/object:argparse.Namespace
env_name: Quadratic_opt
obs_dim: 2
nb_tasks: 3
total_timesteps: 1_000
replay_size: 500
max_episode_steps: 5
eval_freq: 100
log_freq: 50
save_freq: 100_000
burn_in: 20
warm_up: 10
num_evals: 2
batch_size: 2
log_id: test
hidden_dim: 10
context_dim: 8
history_length: 3
curr_task_sampl_prob: 0.5
use_auto_entropy: True